### ISSUE TITLE
Unknown Keybinds

### ISSUE THREAD

**Issue by Ven0m0** [InoriRus/Kyty#51] opened 2022-08-09 16:52 UTC
What are the keybinds for the PS4 buttons. Is enter the ps4 x button. What are the other buttons? A file with the keybinds included would be nice

**Comment by InoriRus** [comment] 2022-08-18 09:55
There is no keyboard mapping for now. You should use real gamepad connected to PC.
Duplicate of #22

**Closed by InoriRus** 2022-08-18 09:55 UTC
