### ISSUE TITLE
Could not find suitable devince in 

### ISSUE THREAD

**Issue by bubbiewolf1212** [InoriRus/Kyty#36] opened 2022-06-03 17:50 UTC
how to fix?

**Comment by bubbiewolf1212** [comment] 2022-06-04 02:26
--- Stack Trace ---
[0] 0000000140286369, 00000001402838c0, Window.cpp.obj, Kyty::Libs::Graphics::VulkanCreate(Kyty::Libs::Graphics::WindowContext*)
[1] 000000014028373b, 00000001402836c0, Window.cpp.obj, Kyty::Libs::Graphics::WindowRun()
[2] 00000001400c1a15, 00000001400c19a0, Kyty.cpp.obj, Kyty::Emulator::LuaFunc::kyty_execute_func(void*)
[3] 0000000140262201, 0000000140261da0, ldo.c.obj, luaD_precall
[4] 000000014026748d, 0000000140266450, lvm.c.obj, luaV_execute
[5] 000000014026251a, 00000001402624b0, ldo.c.obj, luaD_call
[6] 00000001402619af, 0000000140261950, ldo.c.obj, luaD_rawrunprotected
[7] 0000000140262b79, 0000000140262b40, ldo.c.obj, luaD_pcall
[8] 00000001400b393a, 00000001400b3890, lapi.c.obj, lua_pcallk
[9] 000000014007ee31, 000000014007ede0, Scripts.cpp.obj, Kyty::Scripts::Run()
[10] 000000014007efa2, 000000014007ef30, Scripts.cpp.obj, Kyty::Scripts::RunFile(Kyty::Core::String const&)
[11] 0000000140033c1d, 0000000140033060, KytyScripts.cpp.obj, main
[12] 000000014000142a, 000000014000114b, crt2.o, __tmainCRTStartup
--- Error ---

**Comment by InoriRus** [comment] 2022-06-07 09:33
Duplicate of #21

**Closed by InoriRus** 2022-06-07 09:33 UTC
